version: "3.8"
services:
  app:
    build:
      context: .
    restart: always
    ports:
    - 5001:5000
    volumes:
    - ./:/app
  db:
    image: mongo:latest
    restart: always
    volumes:
    - dbdata:/data/db
    - dbconfig:/data/configdb
volumes:
   dbdata:
   dbconfig:


